from auth import AUTH_HEADERS
from personal import PODCAST_NEW_RELEASES_PLAYLIST_ID

BASE_URL = "https://api.spotify.com/v1"

DEFAULT_HEADERS = AUTH_HEADERS

PODCAST_NEW_RELEASES_PLAYLIST_ID = PODCAST_NEW_RELEASES_PLAYLIST_ID